//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.Web.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public string Supplier { get; set; }
    }
}
