//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.Web.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdNumber { get; set; }
        public string Address { get; set; }
        public int BranchID { get; set; }
        public int MembershipTypeID { get; set; }
        public int ClubTypeID { get; set; }
        public string BankName { get; set; }
        public string BanchAcc { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CellNo { get; set; }
        public string TellNo { get; set; }
        public string Occupation { get; set; }
        public string CompanyName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public int StatusID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Club Club { get; set; }
        public virtual Member Members1 { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual MemberShipType MemberShipType { get; set; }
        public virtual Status Status { get; set; }
    }
}
