//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.Web.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberShipType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberShipType()
        {
            this.Members = new HashSet<Member>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> MinimumDuration { get; set; }
        public Nullable<decimal> JoiningFee { get; set; }
        public Nullable<decimal> CardFee { get; set; }
        public string BankName { get; set; }
        public string BranchCode { get; set; }
        public string AccType { get; set; }
        public string Cvvno { get; set; }
        public string CCPayment { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> DebitOrderDate { get; set; }
        public Nullable<decimal> MoneyRecieved { get; set; }
        public string UpfrontMemberShip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
    }
}
