//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMS.Web.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Descritpion { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Supplier { get; set; }
    }
}
